<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void {
        // Delete Israel
        DB::table('countries')->where('iso_code', 'ISR')->delete();

        // Insert comprehensive Arab countries and update list
        $countriesData = [
            // Arab Countries
            ['name' => 'Algeria', 'iso_code' => 'DZA', 'region' => 'Africa'],
            ['name' => 'Bahrain', 'iso_code' => 'BHR', 'region' => 'Middle East'],
            ['name' => 'Comoros', 'iso_code' => 'COM', 'region' => 'Africa'],
            ['name' => 'Djibouti', 'iso_code' => 'DJI', 'region' => 'Africa'],
            ['name' => 'Egypt', 'iso_code' => 'EGY', 'region' => 'Africa'],
            ['name' => 'Iraq', 'iso_code' => 'IRQ', 'region' => 'Middle East'],
            ['name' => 'Jordan', 'iso_code' => 'JOR', 'region' => 'Middle East'],
            ['name' => 'Kuwait', 'iso_code' => 'KWT', 'region' => 'Middle East'],
            ['name' => 'Lebanon', 'iso_code' => 'LBN', 'region' => 'Middle East'],
            ['name' => 'Libya', 'iso_code' => 'LBY', 'region' => 'Africa'],
            ['name' => 'Mauritania', 'iso_code' => 'MRT', 'region' => 'Africa'],
            ['name' => 'Morocco', 'iso_code' => 'MAR', 'region' => 'Africa'],
            ['name' => 'Oman', 'iso_code' => 'OMN', 'region' => 'Middle East'],
            ['name' => 'Palestine', 'iso_code' => 'PSE', 'region' => 'Middle East'],
            ['name' => 'Qatar', 'iso_code' => 'QAT', 'region' => 'Middle East'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SAU', 'region' => 'Middle East'],
            ['name' => 'Somalia', 'iso_code' => 'SOM', 'region' => 'Africa'],
            ['name' => 'Sudan', 'iso_code' => 'SDN', 'region' => 'Africa'],
            ['name' => 'Syria', 'iso_code' => 'SYR', 'region' => 'Middle East'],
            ['name' => 'Tunisia', 'iso_code' => 'TUN', 'region' => 'Africa'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'ARE', 'region' => 'Middle East'],
            ['name' => 'Yemen', 'iso_code' => 'YEM', 'region' => 'Middle East'],

            // Additional Main Countries
            ['name' => 'Afghanistan', 'iso_code' => 'AFG', 'region' => 'Asia'],
            ['name' => 'Albania', 'iso_code' => 'ALB', 'region' => 'Europe'],
            ['name' => 'Angola', 'iso_code' => 'AGO', 'region' => 'Africa'],
            ['name' => 'Armenia', 'iso_code' => 'ARM', 'region' => 'Asia'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZE', 'region' => 'Asia'],
            ['name' => 'Bahamas', 'iso_code' => 'BHS', 'region' => 'Caribbean'],
            ['name' => 'Belarus', 'iso_code' => 'BLR', 'region' => 'Europe'],
            ['name' => 'Belize', 'iso_code' => 'BLZ', 'region' => 'Central America'],
            ['name' => 'Benin', 'iso_code' => 'BEN', 'region' => 'Africa'],
            ['name' => 'Bhutan', 'iso_code' => 'BTN', 'region' => 'Asia'],
            ['name' => 'Bolivia', 'iso_code' => 'BOL', 'region' => 'South America'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BIH', 'region' => 'Europe'],
            ['name' => 'Botswana', 'iso_code' => 'BWA', 'region' => 'Africa'],
            ['name' => 'Brunei', 'iso_code' => 'BRN', 'region' => 'Asia'],
            ['name' => 'Bulgaria', 'iso_code' => 'BGR', 'region' => 'Europe'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BFA', 'region' => 'Africa'],
            ['name' => 'Burundi', 'iso_code' => 'BDI', 'region' => 'Africa'],
            ['name' => 'Cambodia', 'iso_code' => 'KHM', 'region' => 'Asia'],
            ['name' => 'Cameroon', 'iso_code' => 'CMR', 'region' => 'Africa'],
            ['name' => 'Cape Verde', 'iso_code' => 'CPV', 'region' => 'Africa'],
            ['name' => 'Central African Republic', 'iso_code' => 'CAF', 'region' => 'Africa'],
            ['name' => 'Chad', 'iso_code' => 'TCD', 'region' => 'Africa'],
            ['name' => 'Costa Rica', 'iso_code' => 'CRI', 'region' => 'Central America'],
            ['name' => 'Croatia', 'iso_code' => 'HRV', 'region' => 'Europe'],
            ['name' => 'Cuba', 'iso_code' => 'CUB', 'region' => 'Caribbean'],
            ['name' => 'Cyprus', 'iso_code' => 'CYP', 'region' => 'Europe'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZE', 'region' => 'Europe'],
            ['name' => 'Democratic Republic of Congo', 'iso_code' => 'COD', 'region' => 'Africa'],
            ['name' => 'Dominica', 'iso_code' => 'DMA', 'region' => 'Caribbean'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DOM', 'region' => 'Caribbean'],
            ['name' => 'East Timor', 'iso_code' => 'TLS', 'region' => 'Asia'],
            ['name' => 'Ecuador', 'iso_code' => 'ECU', 'region' => 'South America'],
            ['name' => 'El Salvador', 'iso_code' => 'SLV', 'region' => 'Central America'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GNQ', 'region' => 'Africa'],
            ['name' => 'Eritrea', 'iso_code' => 'ERI', 'region' => 'Africa'],
            ['name' => 'Estonia', 'iso_code' => 'EST', 'region' => 'Europe'],
            ['name' => 'Eswatini', 'iso_code' => 'SWZ', 'region' => 'Africa'],
            ['name' => 'Fiji', 'iso_code' => 'FJI', 'region' => 'Oceania'],
            ['name' => 'Gabon', 'iso_code' => 'GAB', 'region' => 'Africa'],
            ['name' => 'Gambia', 'iso_code' => 'GMB', 'region' => 'Africa'],
            ['name' => 'Georgia', 'iso_code' => 'GEO', 'region' => 'Asia'],
            ['name' => 'Greece', 'iso_code' => 'GRC', 'region' => 'Europe'],
            ['name' => 'Grenada', 'iso_code' => 'GRD', 'region' => 'Caribbean'],
            ['name' => 'Guatemala', 'iso_code' => 'GTM', 'region' => 'Central America'],
            ['name' => 'Guinea', 'iso_code' => 'GIN', 'region' => 'Africa'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GNB', 'region' => 'Africa'],
            ['name' => 'Guyana', 'iso_code' => 'GUY', 'region' => 'South America'],
            ['name' => 'Haiti', 'iso_code' => 'HTI', 'region' => 'Caribbean'],
            ['name' => 'Honduras', 'iso_code' => 'HND', 'region' => 'Central America'],
            ['name' => 'Hungary', 'iso_code' => 'HUN', 'region' => 'Europe'],
            ['name' => 'Iceland', 'iso_code' => 'ISL', 'region' => 'Europe'],
            ['name' => 'Iran', 'iso_code' => 'IRN', 'region' => 'Middle East'],
            ['name' => 'Ireland', 'iso_code' => 'IRL', 'region' => 'Europe'],
            ['name' => 'Jamaica', 'iso_code' => 'JAM', 'region' => 'Caribbean'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KAZ', 'region' => 'Asia'],
            ['name' => 'Kenya', 'iso_code' => 'KEN', 'region' => 'Africa'],
            ['name' => 'Kiribati', 'iso_code' => 'KIR', 'region' => 'Oceania'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KGZ', 'region' => 'Asia'],
            ['name' => 'Laos', 'iso_code' => 'LAO', 'region' => 'Asia'],
            ['name' => 'Latvia', 'iso_code' => 'LVA', 'region' => 'Europe'],
            ['name' => 'Lesotho', 'iso_code' => 'LSO', 'region' => 'Africa'],
            ['name' => 'Liberia', 'iso_code' => 'LBR', 'region' => 'Africa'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LIE', 'region' => 'Europe'],
            ['name' => 'Lithuania', 'iso_code' => 'LTU', 'region' => 'Europe'],
            ['name' => 'Luxembourg', 'iso_code' => 'LUX', 'region' => 'Europe'],
            ['name' => 'Madagascar', 'iso_code' => 'MDG', 'region' => 'Africa'],
            ['name' => 'Malawi', 'iso_code' => 'MWI', 'region' => 'Africa'],
            ['name' => 'Maldives', 'iso_code' => 'MDV', 'region' => 'Asia'],
            ['name' => 'Mali', 'iso_code' => 'MLI', 'region' => 'Africa'],
            ['name' => 'Malta', 'iso_code' => 'MLT', 'region' => 'Europe'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MHL', 'region' => 'Oceania'],
            ['name' => 'Micronesia', 'iso_code' => 'FSM', 'region' => 'Oceania'],
            ['name' => 'Moldova', 'iso_code' => 'MDA', 'region' => 'Europe'],
            ['name' => 'Monaco', 'iso_code' => 'MCO', 'region' => 'Europe'],
            ['name' => 'Mongolia', 'iso_code' => 'MNG', 'region' => 'Asia'],
            ['name' => 'Montenegro', 'iso_code' => 'MNE', 'region' => 'Europe'],
            ['name' => 'Mozambique', 'iso_code' => 'MOZ', 'region' => 'Africa'],
            ['name' => 'Myanmar', 'iso_code' => 'MMR', 'region' => 'Asia'],
            ['name' => 'Namibia', 'iso_code' => 'NAM', 'region' => 'Africa'],
            ['name' => 'Nauru', 'iso_code' => 'NRU', 'region' => 'Oceania'],
            ['name' => 'Nepal', 'iso_code' => 'NPL', 'region' => 'Asia'],
            ['name' => 'Nicaragua', 'iso_code' => 'NIC', 'region' => 'Central America'],
            ['name' => 'Niger', 'iso_code' => 'NER', 'region' => 'Africa'],
            ['name' => 'North Macedonia', 'iso_code' => 'MKD', 'region' => 'Europe'],
            ['name' => 'North Korea', 'iso_code' => 'PRK', 'region' => 'Asia'],
            ['name' => 'Panama', 'iso_code' => 'PAN', 'region' => 'Central America'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PNG', 'region' => 'Oceania'],
            ['name' => 'Paraguay', 'iso_code' => 'PRY', 'region' => 'South America'],
            ['name' => 'Portugal', 'iso_code' => 'PRT', 'region' => 'Europe'],
            ['name' => 'Republic of Congo', 'iso_code' => 'COG', 'region' => 'Africa'],
            ['name' => 'Republic of Serbia', 'iso_code' => 'SRB', 'region' => 'Europe'],
            ['name' => 'Romania', 'iso_code' => 'ROU', 'region' => 'Europe'],
            ['name' => 'Rwanda', 'iso_code' => 'RWA', 'region' => 'Africa'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KNA', 'region' => 'Caribbean'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LCA', 'region' => 'Caribbean'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VCT', 'region' => 'Caribbean'],
            ['name' => 'Samoa', 'iso_code' => 'WSM', 'region' => 'Oceania'],
            ['name' => 'San Marino', 'iso_code' => 'SMR', 'region' => 'Europe'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'STP', 'region' => 'Africa'],
            ['name' => 'Senegal', 'iso_code' => 'SEN', 'region' => 'Africa'],
            ['name' => 'Seychelles', 'iso_code' => 'SYC', 'region' => 'Africa'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SLE', 'region' => 'Africa'],
            ['name' => 'Slovakia', 'iso_code' => 'SVK', 'region' => 'Europe'],
            ['name' => 'Slovenia', 'iso_code' => 'SVN', 'region' => 'Europe'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SLB', 'region' => 'Oceania'],
            ['name' => 'South Sudan', 'iso_code' => 'SSD', 'region' => 'Africa'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LKA', 'region' => 'Asia'],
            ['name' => 'Suriname', 'iso_code' => 'SUR', 'region' => 'South America'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJK', 'region' => 'Asia'],
            ['name' => 'Tanzania', 'iso_code' => 'TZA', 'region' => 'Africa'],
            ['name' => 'Timor Leste', 'iso_code' => 'TLS', 'region' => 'Asia'],
            ['name' => 'Togo', 'iso_code' => 'TGO', 'region' => 'Africa'],
            ['name' => 'Tonga', 'iso_code' => 'TON', 'region' => 'Oceania'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TTO', 'region' => 'Caribbean'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TKM', 'region' => 'Asia'],
            ['name' => 'Tuvalu', 'iso_code' => 'TUV', 'region' => 'Oceania'],
            ['name' => 'Uganda', 'iso_code' => 'UGA', 'region' => 'Africa'],
            ['name' => 'Ukraine', 'iso_code' => 'UKR', 'region' => 'Europe'],
            ['name' => 'Uruguay', 'iso_code' => 'URY', 'region' => 'South America'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZB', 'region' => 'Asia'],
            ['name' => 'Vanuatu', 'iso_code' => 'VUT', 'region' => 'Oceania'],
            ['name' => 'Vatican City', 'iso_code' => 'VAT', 'region' => 'Europe'],
            ['name' => 'Zambia', 'iso_code' => 'ZMB', 'region' => 'Africa'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZWE', 'region' => 'Africa'],
        ];

        DB::table('countries')->insertOrIgnore($countriesData);
    }

    public function down(): void {
        DB::table('countries')->where('iso_code', 'ISR')->delete();
    }
};
